=== isaccanedo/schematized/examples/schemas/user1&2.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "description": "User data from server.",
  "maxProperties": 24,
  "minProperties": 23,
  "properties": {
    "userRole": {
      "type": "array",
      "items": {
        "type": "string",
        "maxLength": 13,
        "minLength": 8
      }
    },
    "name": {
      "type": "string",
      "maxLength": 11,
      "minLength": 11
    },
    "displayName": {
      "type": "string",
      "maxLength": 6,
      "minLength": 3
    },
    "lastLogin": {
      "anyOf": [
        {
          "type": "null"
        },
        {
          "type": "string",
          "maxLength": 20,
          "minLength": 20,
          "format": "date-time"
        }
      ]
    },
    "missingNecessaryLicenseAgreement": {
      "type": "boolean"
    },
    "availableApps": {
      "type": "string",
      "maxLength": 75,
      "minLength": 63
    },
    "enabledApps": {
      "type": "array",
      "items": {
        "type": "string",
        "maxLength": 10,
        "minLength": 7
      }
    },
    "betaFeatures": {
      "anyOf": [
        {
          "type": "null"
        },
        {
          "type": "array",
          "items": {
            "type": "string",
            "maxLength": 16,
            "minLength": 13
          }
        }
      ]
    },
    "settings": {
      "type": "array"
    },
    "canSignCerts": {
      "type": "boolean"
    },
    "appUserId": {
      "type": "number",
      "maximum": 100000,
      "minimum": 47
    },
    "email": {
      "type": "string",
      "maxLength": 25,
      "minLength": 18,
      "format": "email"
    },
    "username": {
      "type": "string",
      "maxLength": 8,
      "minLength": 4
    },
    "userCountry": {
      "type": "string",
      "maxLength": 3,
      "minLength": 3
    },
    "himsAccess": {
      "type": "boolean"
    },
    "enabledFeatures": {
      "type": "array",
      "items": {
        "type": "string",
        "maxLength": 13,
        "minLength": 3
      }
    },
    "vetTechId": {
      "type": "number",
      "maximum": 38,
      "minimum": 38
    },
    "clinicId": {
      "type": "number",
      "maximum": 100000,
      "minimum": 3
    },
    "clinicName": {
      "type": "string",
      "maxLength": 20,
      "minLength": 20
    },
    "clinicAnimalType": {
      "type": "null"
    },
    "includeImage": {
      "type": "boolean"
    },
    "giveNewContactsMvlAccess": {
      "type": "boolean"
    },
    "account": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "maxLength": 6,
          "minLength": 6
        },
        "name": {
          "type": "string",
          "maxLength": 20,
          "minLength": 13
        },
        "id": {
          "type": "number",
          "maximum": 100000,
          "minimum": 3
        },
        "plan": {
          "type": "string",
          "maxLength": 4,
          "minLength": 4
        },
        "territory": {
          "type": "string",
          "maxLength": 7,
          "minLength": 7
        },
        "address1": {
          "type": "string",
          "maxLength": 15,
          "minLength": 1
        },
        "address2": {
          "type": "string",
          "maxLength": 14,
          "minLength": 9
        },
        "city": {
          "type": "string",
          "maxLength": 6,
          "minLength": 4
        },
        "postalcode": {
          "type": "string",
          "maxLength": 5,
          "minLength": 5
        },
        "state": {
          "type": "string",
          "maxLength": 2,
          "minLength": 2
        },
        "country": {
          "type": "string",
          "maxLength": 3,
          "minLength": 3
        }
      },
      "required": [
        "address1",
        "address2",
        "city",
        "country",
        "id",
        "name",
        "plan",
        "postalcode",
        "state",
        "territory",
        "type"
      ],
      "additionalProperties": false,
      "maxProperties": 11,
      "minProperties": 11
    },
    "missingNecesaryLicenseAgreement": {
      "type": "boolean"
    },
    "licenseStates": {
      "type": "array",
      "items": {
        "type": "string",
        "maxLength": 7,
        "minLength": 2
      }
    },
    "vetId": {
      "type": "number",
      "maximum": 1,
      "minimum": 1
    }
  },
  "required": [
    "account",
    "appUserId",
    "availableApps",
    "betaFeatures",
    "canSignCerts",
    "clinicAnimalType",
    "clinicId",
    "clinicName",
    "displayName",
    "email",
    "enabledApps",
    "enabledFeatures",
    "giveNewContactsMvlAccess",
    "himsAccess",
    "includeImage",
    "lastLogin",
    "name",
    "settings",
    "userCountry",
    "userRole",
    "username"
  ],
  "title": "/user response",
  "type": "object"
}

=== isaccanedo/schematized/examples/objects/account-info2.json
{
  "userRole": [
    "ROLE_VET"
  ],
  "name": "John Sample",
  "displayName": "Sample",
  "lastLogin": "2020-06-10T22:29:36Z",
  "missingNecesaryLicenseAgreement": false,
  "availableApps": "appEquuslink,appFeedlink,appHealthlink,appManager,appScriptlink",
  "enabledApps": [
    "equuslink",
    "feedlink",
    "healthlink",
    "manager",
    "scriptlink"
  ],
  "betaFeatures": [
    "managerCreateDoc",
    "forSaleAccess"
  ],
  "settings": [],
  "canSignCerts": true,
  "appUserId": 100000,
  "email": "bsteele@globalvetlink.com",
  "username": "vet1",
  "userCountry": "USA",
  "himsAccess": false,
  "enabledFeatures": [
    "Ads",
    "Rabies",
    "International"
  ],
  "licenseStates": [
    "AZ",
    "IA",
    "ID",
    "WA",
    "MN",
    "LA",
    "CO",
    "AK",
    "MI",
    "FEDERAL",
    "TX",
    "NE",
    "GA",
    "SD",
    "AL",
    "DC",
    "KS",
    "IN",
    "WI",
    "KY",
    "MO",
    "IL",
    "NY",
    "CA",
    "ND",
    "OK",
    "VA",
    "FL",
    "TN"
  ],
  "vetId": 1,
  "clinicId": 100000,
  "clinicName": "Ames Animal Hospital",
  "clinicAnimalType": null,
  "includeImage": true,
  "giveNewContactsMvlAccess": true,
  "account": {
    "type": "Clinic",
    "name": "Ames Hospital",
    "id": 100000,
    "plan": "PAID",
    "territory": "Eastern",
    "address1": "a",
    "address2": "Suite 300",
    "city": "Ankeny",
    "postalcode": "50021",
    "state": "FL",
    "country": "USA"
  }
}
