=== isaccanedo/schematized/examples/schemas/user.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "maxProperties": 23,
  "minProperties": 23,
  "properties": {
    "userRole": {
      "type": "array",
      "items": {
        "type": "string",
        "maxLength": 13,
        "minLength": 13
      }
    },
    "name": {
      "type": "string",
      "maxLength": 11,
      "minLength": 11
    },
    "displayName": {
      "type": "string",
      "maxLength": 3,
      "minLength": 3
    },
    "lastLogin": {
      "type": "null"
    },
    "missingNecessaryLicenseAgreement": {
      "type": "boolean"
    },
    "availableApps": {
      "type": "string",
      "maxLength": 75,
      "minLength": 75
    },
    "enabledApps": {
      "type": "array",
      "items": {
        "type": "string",
        "maxLength": 10,
        "minLength": 7
      }
    },
    "betaFeatures": {
      "type": "null"
    },
    "settings": {
      "type": "array"
    },
    "canSignCerts": {
      "type": "boolean"
    },
    "appUserId": {
      "type": "number",
      "maximum": 47,
      "minimum": 47
    },
    "email": {
      "type": "string",
      "maxLength": 18,
      "minLength": 18,
      "format": "email"
    },
    "username": {
      "type": "string",
      "maxLength": 8,
      "minLength": 8
    },
    "userCountry": {
      "type": "string",
      "maxLength": 3,
      "minLength": 3
    },
    "himsAccess": {
      "type": "boolean"
    },
    "enabledFeatures": {
      "type": "array",
      "items": {
        "type": "string",
        "maxLength": 13,
        "minLength": 3
      }
    },
    "vetTechId": {
      "type": "number",
      "maximum": 38,
      "minimum": 38
    },
    "clinicId": {
      "type": "number",
      "maximum": 3,
      "minimum": 3
    },
    "clinicName": {
      "type": "string",
      "maxLength": 20,
      "minLength": 20
    },
    "clinicAnimalType": {
      "type": "null"
    },
    "includeImage": {
      "type": "boolean"
    },
    "giveNewContactsMvlAccess": {
      "type": "boolean"
    },
    "account": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "maxLength": 6,
          "minLength": 6
        },
        "name": {
          "type": "string",
          "maxLength": 20,
          "minLength": 20
        },
        "id": {
          "type": "number",
          "maximum": 3,
          "minimum": 3
        },
        "plan": {
          "type": "string",
          "maxLength": 4,
          "minLength": 4
        },
        "territory": {
          "type": "string",
          "maxLength": 7,
          "minLength": 7
        },
        "address1": {
          "type": "string",
          "maxLength": 15,
          "minLength": 15
        },
        "address2": {
          "type": "string",
          "maxLength": 14,
          "minLength": 14
        },
        "city": {
          "type": "string",
          "maxLength": 4,
          "minLength": 4
        },
        "postalcode": {
          "type": "string",
          "maxLength": 5,
          "minLength": 5
        },
        "state": {
          "type": "string",
          "maxLength": 2,
          "minLength": 2
        },
        "country": {
          "type": "string",
          "maxLength": 3,
          "minLength": 3
        }
      },
      "required": [
        "address1",
        "address2",
        "city",
        "country",
        "id",
        "name",
        "plan",
        "postalcode",
        "state",
        "territory",
        "type"
      ],
      "additionalProperties": false,
      "maxProperties": 11,
      "minProperties": 11
    }
  },
  "required": [
    "account",
    "appUserId",
    "availableApps",
    "betaFeatures",
    "canSignCerts",
    "clinicAnimalType",
    "clinicId",
    "clinicName",
    "displayName",
    "email",
    "enabledApps",
    "enabledFeatures",
    "giveNewContactsMvlAccess",
    "himsAccess",
    "includeImage",
    "lastLogin",
    "missingNecessaryLicenseAgreement",
    "name",
    "settings",
    "userCountry",
    "userRole",
    "username",
    "vetTechId"
  ],
  "type": "object"
}

=== isaccanedo/schematized/examples/objects/account-info.json
{
    "userRole": [
        "ROLE_VET_TECH"
    ],
    "name": "VetTech One",
    "displayName": "One",
    "lastLogin": null,
    "missingNecessaryLicenseAgreement": true,
    "availableApps": "appFeedlink,appDatalink,appEquuslink,appManager,appHealthlink,appScriptlink",
    "enabledApps": [
        "feedlink",
        "datalink",
        "equuslink",
        "manager",
        "healthlink",
        "scriptlink"
    ],
    "betaFeatures": null,
    "settings": [],
    "canSignCerts": false,
    "appUserId": 47,
    "email": "vettech1@email.com",
    "username": "vettech1",
    "userCountry": "USA",
    "himsAccess": false,
    "enabledFeatures": [
        "NVSL",
        "Rabies",
        "International",
        "Ads"
    ],
    "vetTechId": 38,
    "clinicId": 3,
    "clinicName": "Ames Animal Hospital",
    "clinicAnimalType": null,
    "includeImage": true,
    "giveNewContactsMvlAccess": true,
    "account": {
        "type": "Clinic",
        "name": "Ames Animal Hospital",
        "id": 3,
        "plan": "PAID",
        "territory": "Midwest",
        "address1": "123 Main Street",
        "address2": "Ames, IA 50014",
        "city": "Ames",
        "postalcode": "50014",
        "state": "IA",
        "country": "USA"
    }
}
